ContactAppMVCNhibernate/Controllers/ContactAjaxController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ContactAppMVCNhibernate.Data;
using ContactAppMVCNhibernate.Models;

namespace ContactAppMVCNhibernate.Controllers
{
    public class ContactAjaxController : Controller
    {
        // GET: ContactAjax
        public ActionResult Index(int userId)
        {
            Session["userid"] = userId;

            using (var session = NHibernateHelper.CreateSession())
            {
                return View();
            }
        }

        public ActionResult GetContactsForAdmin(int userId)
        {

            using (var session = NHibernateHelper.CreateSession())
            {
                var contacts = session.Query<Contact>().Where(c => c.User.UserId == userId).ToList();
                return View(contacts);
            }
        }

        public ActionResult GetAllContacts()
        {

            int userId = (int)Session["userId"];
            using (var session = NHibernateHelper.CreateSession())
            {
                var contacts = session.Query<Contact>()
                    .Where(c => c.User.UserId == userId)
                    .Select(c => new Contact
                    {
                        ContactId = c.ContactId,
                        FName = c.FName,
                        LName = c.LName,
                        IsActive = c.IsActive,
                    }).
                    ToList();
                return Json(contacts, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult ActiveContacts()
        {
            var userId = Session["userId"];
            using (var session = NHibernateHelper.CreateSession())
            {
                var contacts = session.Query<Contact>()
                    .Where(c => c.User.UserId == (int)userId)
                    .Where(c => c.IsActive == true)
                    .Select(c => new Contact
                    {
                        ContactId = c.ContactId,
                        FName = c.FName,
                        LName = c.LName,
                        IsActive = c.IsActive,
                    }).
                    ToList();
                return PartialView("_ActiveContacts", contacts);
            }
        }


        [Authorize(Roles = "Staff")]
        public ActionResult Create()
        {
            return PartialView("_Create");
        }

        [Authorize(Roles = "Staff")]
        [HttpPost]
        public ActionResult Create(Contact contact)
        {
            using (var session = NHibernateHelper.CreateSession())
            {
                var userId = Session["userid"];
                using (var txn = session.BeginTransaction())
                {
                    var user = session.Query<User>().FirstOrDefault(e => e.UserId == (int)userId);
                    contact.IsActive = true;
                    contact.User = user;
                    session.Save(contact);
                    txn.Commit();
                    //return PartialView("_ContactList",);
                  //  return RedirectToAction("Index", "ContactAjax", new { userId = Session["userid"] });
                   return Json(new {success=true});
                }
            }
        }

        [Authorize(Roles = "Staff")]
        public ActionResult Edit(int contactId)
        {
            using (var session = NHibernateHelper.CreateSession())
            {
                var contact = session.Get<Contact>(contactId);
                return PartialView("_Edit", contact);  
            }
        }

        [Authorize(Roles = "Staff")]
        [HttpPost]
        public ActionResult Edit(Contact contact)
        {
            using (var session = NHibernateHelper.CreateSession())
            {
                using (var txn = session.BeginTransaction())
                {
                    var existingContact = session.Get<Contact>(contact.ContactId);

                    if (existingContact != null)
                    {
                        existingContact.FName = contact.FName;
                        existingContact.LName = contact.LName;
                        session.Update(existingContact);
                        txn.Commit();
                    }

                    return RedirectToAction("Index", "ContactAjax", new { userId = Session["userid"] });
                }
            }
        }

        [Authorize(Roles = "Staff")]
        [HttpPost]
        public ActionResult ToggleActiveStatus(int contactId, bool isActive)
        {
            using (var session = NHibernateHelper.CreateSession())
            {
                using (var txn = session.BeginTransaction())
                {
                    // Fetch the user based on userId
                    var contact = session.Query<Contact>().FirstOrDefault(u => u.ContactId == contactId);
                    if (contact != null)
                    {
                        contact.IsActive = isActive;

                        session.Update(contact);
                        txn.Commit();
                        return Json(new { success = true, message = isActive ? "User reactivated." : "User deactivated." });
                    }
                    return Json(new { success = false, message = "User not found." });
                }

            }
        }


    }
}

ContactAppMVCNhibernate/Controllers/ContactDetailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ContactAppMVCNhibernate.Data;
using ContactAppMVCNhibernate.Models;

namespace ContactAppMVCNhibernate.Controllers
{
    [Authorize]
    public class ContactDetailController : Controller
    {
        // GET: ContactDetail
        public ActionResult Index(int contactId)
        {
            Session["contactid"] = contactId;

            return View();
        }

        //public ActionResult GetData(int page, int rows, string sidx, string sord, string searchString)
        //{
        //    var contactId = Session["contactid"]; // Ensure contactId is in session
        //    using (var session = NHibernateHelper.CreateSession())
        //    {
        //        var contactDetails = session.Query<ContactDetail>()
        //            .Where(c => c.Contact.ContactId == (int)contactId) // Filter by ContactId
        //            .ToList();

        //        int totalCount = contactDetails.Count();
        //        int totalPages = (int)Math.Ceiling((double)totalCount / rows);

        //        var jsonData = new
        //        {
        //            total = totalPages,  // Total number of pages
        //            page = page,         // Current page
        //            records = totalCount, // Total number of records
        //            rows = (from detail in contactDetails
        //                    orderby sidx + " " + sord
        //                    select new
        //                    {
        //                        id = detail.ContactDetailId, 
        //                        cell = new string[] {
        //                            detail.ContactDetailId.ToString(),
        //                            detail.Type,  
        //                            detail.Email
        //                        }
        //                    }).Skip((page - 1) * rows).Take(rows).ToArray()
        //        };
        //        return Json(jsonData, JsonRequestBehavior.AllowGet);
        //    }
        //}

        public ActionResult GetData(int page, int rows, string sidx, string sord, bool _search, string searchField, string searchString, string searchOper)
        {
            using (var session = NHibernateHelper.CreateSession())
            {
                var contactId = Session["contactId"]; // Ensure contactId is in session

                var detailList = session.Query<ContactDetail>()
                    .Where(c => c.Contact.ContactId == (int)contactId) // Filter by contactId
                    .ToList();

                if (_search && searchField == "Email" && searchOper == "eq")
                {
                    detailList = detailList.Where(p => p.Email == searchString).ToList();
                }

                int totalCount = detailList.Count();
                int totalPages = (int)Math.Ceiling((double)totalCount / rows);

                switch (sidx)
                {
                    case "Email":
                        detailList = sord == "asc" ? detailList.OrderBy(p => p.Email).ToList()
                            : detailList.OrderByDescending(p => p.Email).ToList();
                        break;

                    case "Type":
                        detailList = sord == "asc" ? detailList.OrderBy(p => p.Type).ToList()
                            : detailList.OrderByDescending(p => p.Type).ToList();
                        break;
                }

                var jsonData = new
                {
                    total = totalPages,
                    page = page,
                    records = totalCount,
                    rows = detailList.Select(detail => new
                    {
                        cell = new string[]
                        {
                    detail.ContactDetailId.ToString(),
                    detail.Email,
                    detail.Type
                        }
                    }).Skip((page - 1) * rows).Take(rows).ToArray()
                };

                return Json(jsonData, JsonRequestBehavior.AllowGet);
            }
        }

        [Authorize(Roles = "Staff")]

        public ActionResult Add(ContactDetail contactDetail)
        {
            using (var session = NHibernateHelper.CreateSession())
            {
                var contactId = Session["contactid"];
                using (var txn = session.BeginTransaction())
                {
                    var contact = session.Query<Contact>().FirstOrDefault(e => e.ContactId == (int)contactId);

                    contactDetail.Contact = contact;
                    session.Save(contactDetail);
                    txn.Commit();

                    //var id = products.Max(i => i.Id);
                    //product.Id = id + 1;
                    //products.Add(product);
                    return Json(new { success = true, message = "Added New Detail" });
                }
            }

        }
        //[Authorize(Roles = "Staff")]

        //public ActionResult Delete(int detailId)
        //{
        //    using (var session = NHibernateHelper.CreateSession())
        //    {
        //        var contactId = Session["contactid"];
        //        using (var txn = session.BeginTransaction())
        //        {

        //            var targetDetail = session.Get<ContactDetail>(detailId);
        //            session.Delete(targetDetail);
        //            txn.Commit();
        //            return Json(new { success = true, message = "Product deeleted successfuffy" });

        //        }
        //    }

        //}
        [Authorize(Roles = "Staff")]
        public ActionResult Delete(int id)
        {
            using (var session = NHibernateHelper.CreateSession())

            {
                using (var transaction = session.BeginTransaction())
                {
                    var contactDetail = session.Query<ContactDetail>().FirstOrDefault(cd => cd.ContactDetailId == id);

                    session.Delete(contactDetail);

                    transaction.Commit();

                    return Json(new { success = true, message = "Contact Detail Deleted Successfully" });

                }

            }

        }

        [Authorize(Roles = "Staff")]
        public ActionResult Edit(ContactDetail detail)
        {
            using (var session = NHibernateHelper.CreateSession())
            {
                using (var txn = session.BeginTransaction())
                {
                    var existingContactDetail = session.Get<ContactDetail>(detail.ContactDetailId);
                    if (existingContactDetail != null)
                    {
                        existingContactDetail.Type = detail.Type;
                        existingContactDetail.Email = detail.Email;

                        session.Update(existingContactDetail);
                        txn.Commit();
                        return Json(new { success = true, message = "Detail edited successfully" });
                    }
                    else
                    {
                        return Json(new { success = false, message = "Detail not found" });
                    }
                }
            }
        }
    }

}

    
        
        
    

ContactAppMVCNhibernate/Views/ContactAjax/GetContactsForAdmin.cshtml
@model IEnumerable<ContactAppMVCNhibernate.Models.Contact>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsActive)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsActive)
        </td>
        <td>
            @Html.ActionLink("Contact Details", "Index", "ContactDetail", new { contactid = item.ContactId }, null)
        </td>
    </tr>
}

</table>

ContactAppMVCNhibernate/Views/ContactAjax/Index.cshtml
@model IEnumerable<ContactAppMVCNhibernate.Models.Contact>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Index";
}
<br />
<h2 style="text-align: center;"><strong><u>Contact List</u></strong></h2>
<br />
<hr />
<div id="contact-list">
    <br />
    @if (User.IsInRole("Staff"))
    {
        <p>
            <button type="button" class="btn btn-outline-danger" id="btnAdd">
                Add  new
            </button>
        </p>
    }
    <br />
    <table class="table">
        <thead>
            <tr>
                <th>
                    FName
                </th>
                <th>
                    LName
                </th>
                <th>
                    Current Status
                </th>
                <th>Actions</th>
                <th></th>

            </tr>
        </thead>

        <tbody id="tblBody">
        </tbody>
    </table>
</div>

<div id="active-contacts" style="display:none;">
    <!-- Partial view will be loaded here -->
</div>

<div id="contact-create" style="display:none;">
    <!-- Partial view will be loaded here -->
    @Html.Partial("_Create")
</div>

<div id="contact-edit" style="display:none;">
    <!-- Partial view will be loaded here -->
</div>
<!-- Rest of the code remains the same -->

<script src="~/Scripts/ContactCrud.js"></script>

<script>
    $(document).ready(function () {
        loadContacts();
    });

    function loadActiveContacts() {
    $.ajax({
        type: "GET",
        url: '@Url.Action("ActiveContacts", "ContactAjax")',
        success: function (data) {
            $("#active-contacts").html(data);
            $("#contact-list").hide();
            $("#contact-create").hide();

            $("#active-contacts").show();
        }
    });
}
</script>
<style>
    button.btn-info {
        padding: 8px 12px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        font-size: 14px;
        width: 150px; /* or any fixed width you prefer */
    }
</style>

ContactAppMVCNhibernate/Views/ContactAjax/_Edit.cshtml
@model ContactAppMVCNhibernate.Models.Contact

<div id="contact-edit-form">
    <br />
    <h4>Edit Contact</h4>
    <hr />
    <form id="edit-contact-form">
        <br />
        <input type="hidden" name="ContactId" value="@Model.ContactId" />
        <div class="form-group">
            <label for="FName">First Name:</label>
            <input type="text" name="FName" value="@Model.FName" class="form-control" required />
        </div>
        <br />
        <div class="form-group">
            <label for="LName">Last Name:</label>
            <input type="text" name="LName" value="@Model.LName" class="form-control" required />
        </div>
        <br />
        <button type="submit" class="btn btn-success" id="btn-success">Save</button>
    </form>
</div>

<style>
    #contact-edit-form {
        text-align: center;
        max-width: 500px;
        margin: 0 auto;
        padding: 20px;
        border: 1px solid #ddd;
        border-radius: 10px;
        background-color: #222222;
        color: white;
    }

    #btn-success {
        width: 80%;
        display: block;
        margin: 0 auto;
    }
</style>

ContactAppMVCNhibernate/Views/ContactAjax/_GetAllContacts.cshtml
@model IEnumerable<ContactAppMVCNhibernate.Models.Contact>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsActive)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsActive)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ContactId }) |
            @Html.ActionLink("Details", "Details", new { id=item.ContactId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ContactId })
        </td>
    </tr>
}

</table>